theme: jekyll-theme-cayman
title: Dom McKellar | GetSeo
description: GetSeo was created by Dominic McKellar. It's a CLI built in Ruby that allows you to quickly and easily inspect various SEO metrics from any website.
